export const catagory = [
  { id: 1, catagory: "Home", emoji: "🏠" },
  { id: 2, catagory: "Work", emoji: "🏢" },
  { id: 3, catagory: "Personal", emoji: "👤" },
  { id: 4, catagory: "Health/Fitness", emoji: "💪" },
  { id: 5, catagory: "Education", emoji: "📚" },
  { id: 6, catagory: "Gym", emoji: "🏋️" },
  { id: 7, catagory: "Shopping", emoji: "🛒" },
  { id: 8, catagory: "Finance", emoji: "💰" },
  { id: 9, catagory: "Travel", emoji: "✈️" },
  { id: 10, catagory: "Hobbies", emoji: "🎨" },
  { id: 11, catagory: "Events", emoji: "📅" },
  { id: 12, catagory: "Projects", emoji: "📁" },
  { id: 13, catagory: "Family", emoji: "👪" },
];
